### ISSUE TITLE
Slow F2FS Writing Speed

### ISSUE THREAD

**Issue by X9VoiD** [dorimanx/Dorimanx-LG-G2-D802-Kernel#11]
Well... ummm... maybe a little odd but... I am experiencing slow writing speed on /cache formatted with f2fs...

On Ext4 it gives me up to 37.5 mb/s writing speed
On F2FS it gives me up to 32 mb/s writing speed

I have not yet tested it on other partitions ( /data /system )

**Comment by dorimanx** [comment]
test is constant? do 5 runs. and take the average.
with same i/o scheduler and make sure I/O on other partitions is not used. and cpu is IDLE.

i am sure that you didnt know thing that i will reveal to you now:

device has ONE storage = 32GB it's type of sdcard. RAW nothing there.

Now we split this storage to parts! data/system/cache/ many other small ROM/Modem parts.

and large part for FUSE mount to be fat32 for storage. that is part of data partition.

Now you test cache and tell me that I/O speed is less... but it's just one part of the same RAW sdcard!

So if something using I/O for system or data at the same time you test, you will get LESS. as global I/O is used too.

now retest and provide correct values.

**Comment by X9VoiD** [comment]
I already know that... And speaking of "I know that" we can resize these partitions... And on android, the name of the storage media is mmcblk0 and its partitions are like this "mmcblk0p1"

For the cache it is mmcblk0p35 right?

So going back to the topic, I have retested it again and here is what I do... and the environment...

I/O Sched = SIO
Reboot...
I've waited for 5 mins...
TRIM (f2fs does it on background)
Use Greenify to stop background apps (including system apps)
Run the test
Record
Repeat...

And here is the average results...

ext4 = 34 mb/s
f2fs = 40.2 mb/s

I do see it now :D

But still.. F2FS shows slow writing speed compared to the speed it displays (normally 100 mb/s to 280 mb/s)

Side Question: Is F2FS slow if the partition is small? Because it will only get small amounts of nodes...

**Comment by X9VoiD** [comment]
Ill try to run tests without booting into android...

**Comment by dorimanx** [comment]
yes it's possible that it's maybe slow as partition is small.

also the write speed of 100 to 280 is fake. it's ram cached write
first to RAM then to storage chunk by chunk,

REAL write speed is from 16mb to 30mb in RAW storage.
and if real sdcard used in slot (lg dont have) then write speed is even less!

10 to 25mb max.

**Comment by X9VoiD** [comment]
The Final Verdict:

  F2FS

```
  42 mb/s RAW
```

  Ext4

```
  36 mb/s RAW
```

Case closed

**Comment by dorimanx** [comment]
Great, thanks for testing. Very good results, more than i have expected :-)

**Comment by jgcaaprom** [comment]
Great explanation
