### ISSUE TITLE
panel information

### ISSUE THREAD

**Issue by shminer** [dorimanx/Dorimanx-LG-G2-D802-Kernel#14]
I found this 
https://github.com/JackpotClavin/android_kernel_lge_msm8974/commit/261c8773f5d7fc2ba44b29f0af64f1bc3aaab852
https://github.com/JackpotClavin/android_kernel_lge_msm8974/commit/c614c4e39816535210da52363b0fd3ff2b24ca1e
https://github.com/JackpotClavin/android_kernel_lge_msm8974/commit/247206ce2ffbe0ae568238305e81a23858dc3e34

**Comment by dorimanx** [comment]
nice, but not needed, it's for adding ONE panel type incase it's missing from command line.
what about the other one?
we have script that do all that needed. and i have added default panel type to kernel command line.

anyway if user have KK bootloader, this is no longer needed! as it's added by KK boot loader.
Kernel is Bumped and booting with KK bootloader.

Commits are useless to me.

Thanks.
