### ISSUE TITLE
Sound quality decrease... 

### ISSUE THREAD

**Issue by DarkKV** [dorimanx/Dorimanx-LG-G2-D802-Kernel#2]
Headphone sound quality has decreased since the audio driver has been changed.

**Comment by dorimanx** [comment]
any real proof? i dont hear any thing wrong.
what you just did is OPEN new JUNK issue. what you are a kid?
Here you dont have dmesg or stacktrace or real proof, dont bother to open issues. it's not XDA.

i give you 1 day. then close.

**Comment by DarkKV** [comment]
Well apart from the difference that you can ACTUALLY hear... Maybe you're not using decent headphones?
Also the fact that it's an actual difference with the way the driver outputs the audio posting a dmesg / stacktrace would be silly. 
I'll give you the benefit of the doubt and take into account the fact you're constantly bombarded with 'kids' asking the same questions constantly over and over again at XDA.

Here I've closed it for you, sorry for wasting your time on something I feel is an issue. Thanks for the reply though.
