### ISSUE TITLE
LG G2 F320L FM Radio not working... (using CloudyG3 2.1)

### ISSUE THREAD

**Issue by X9VoiD** [dorimanx/Dorimanx-LG-G2-D802-Kernel#5]
There are guys on XDA which proposed a solution for that... there is the link

http://forum.xda-developers.com/showpost.php?p=54068182&postcount=8038

**Comment by dorimanx** [comment]
are you sure that F320L has radio chip and hardware support?
any way, Enabled for F320\* + code add to KR gpiomux

Need to TEST.
https://github.com/dorimanx/Dorimanx-LG-G2-D802-Kernel/commit/4a8a23dc99720f9f2ac1110eeb7b8f6792a5c79e
https://github.com/dorimanx/Dorimanx-LG-G2-D802-Kernel/commit/56d14fff0b482a3d1b3c88a260e00efaced9f501

**Comment by X9VoiD** [comment]
On Lightning Rom... it was working...
It was working until I flashed Dorimanx Kernel...

Then.. CloudyG3 obviously supports fm radio but with Dorimanx Kernel, it is disabled... Cant enable the fm radio using OEM Propriority API and also low level access..

LG G2 F320L does support fm radio but is disabled on kernel level...

Hey! Can you guys please help me recompile this new source code??? Or upload an already flashable one...

(Im still setting up my developer environment on my ubuntu 13.10 and I would be happy if someone says me what I need to perform compilations to Dorimanx Kernel Source Code)

**Comment by dorimanx** [comment]
here is a TEST build with Radio code enabled for F320 ALL.
http://www.dorimanx.com/radio-test/Kernel-Dorimanx-V9.8.1-KK-[10-00]-[29-01]-LG-F320-PWR-CORE.zip
Let me know what you get.

**Comment by X9VoiD** [comment]
Sorry for inactivity... Ill flash it now...

**Comment by X9VoiD** [comment]
Unfortunately... the new patch results to stucked boot

**Comment by X9VoiD** [comment]
I'll try to flash stock fm radio...

**Comment by dorimanx** [comment]
same result for all my F320 users.
No FM RADIO for F320. sorry. case closed.
