### ISSUE TITLE
Was this normal? (Suspicious Errors Found)

### ISSUE THREAD

**Issue by X9VoiD** [dorimanx/Dorimanx-LG-G2-D802-Kernel#6]
<3>mmc2: SDIO interrupt recieved without function driver claiming an irq
<3>init: /init.galbi.rc: 1126: invalid service name 'moca_service_disable'
<3>init: could not import file '/init.vmware.rc' from '/init.rc'
<3>init: invalid uid 'fm_radio'
<3>init: invalid uid 'fm_radio'
<3>init: invalid uid 'nfclock'
<6>keychord: using input dev s2w_pwrkey for fevent
<6>keychord: using input dev qpnp_pon for fevent
<6>keychord: using input dev gpio-keys for fevent
<6>keychord: using input dev hs_detect for fevent
<3>init: cannot open '/initlogo.rle'
<3>init: [get_was_hidden_reset] set ro.lge.hiddenreset 0 --->

**Comment by dorimanx** [comment]
yes, normal. see STOCK kernel warnings. same + lots more that i cleaned already.
