### ISSUE TITLE
F2FS Mounting Errors

### ISSUE THREAD

**Issue by X9VoiD** [dorimanx/Dorimanx-LG-G2-D802-Kernel#9]
If I use TWRP 2.8 and change a filesystem to F2FS.... For testing purposes, I chosed the /cache partition... It works on TWRP... Everything except the MTP starts to get bugged (TWRP issues?)

Once you reboot to system.... It will not be mounted correctly... The /cache can be seen and is readable but you cannot write on it... Same on every partition... It seems like it is mounted in read-only mode and that's the reason why I or "WE" get a bootloop right?

**Comment by X9VoiD** [comment]
I think it is on the kernel side, which has a bugged or incorrect implementation of F2FS FileSystem... I don't know but, maybe? Just a guess

**Comment by dorimanx** [comment]
Selinux. that is the problem.

Need to mount partition with security options for selinux.
if you boot with permissive mode in selinux all OK.

It's mounting and ROM side bug. Selinux want ext4 options.

EXT4
/dev/block/platform/msm_sdcc.1/by-name/userdata on /data type ext4 (rw,seclabel,nosuid,nodev,noatime,nodiratime,noauto_da_alloc,resuid=1000,errors=continue,data=ordered)

we need 
seclabel,resuid=1000

**Comment by dorimanx** [comment]
Look here:
https://android-review.googlesource.com/#/c/96593/1/fs_use

to have seclabel we need this.
and we cant use resuid=1000, not supported in F2FS. will work without it.
